services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: demodb
    ports: 
      - "5432:5432"
  web:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      JWT_SECRET: ${JWT_SECRET}
      HASH_SECRET: ${HASH_SECRET}
      DATABASE_URL: postgres://postgres:mysecretpassword@db:5432/demodb
    ports:
      - "3000:3000"
